# -*- coding: utf-8 -*-
"""DataFrame - Covid-19 nos países

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hOW8GThEl6NSoB0QW_ByJjl1ODpr1_Xj
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt



df = pd.read_csv('/content/covid_worldwide.csv', sep=';')
df.head(10)

# cria um DataFrame de exemplo
data = {'Country': ['USA', 'Brazil', 'India', 'Russia', 'UK'],
        'Total Cases': [329289, 157837, 190609, 84532, 306293],
        'Active Cases': [157326, 51647, 91707, 19918, 273092]}

df = pd.DataFrame(data)

#cria um gráfico de barras comparando as colunas 'Total Cases' e 'Active Cases'

ax = df.plot(x='Country', y=['Total Cases', 'Active Cases'], kind='bar')

# adiciona um título e rótulos de eixo
ax.set_title('Comparação entre Total Cases e Active Cases por país')
ax.set_xlabel('Países')
ax.set_ylabel('Número de casos')

# exibe o gráfico
plt.show()

#Este código criará um gráfico de barras que compara as colunas 'Total Cases' e 'Active Cases' por país. Cada país será exibido com duas barras, uma para o número total de casos e outra para o número de casos ativos.